// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/sterligov/otus_highload/dating/internal/config"
	"github.com/sterligov/otus_highload/dating/internal/gateway/sql"
	internalhttp "github.com/sterligov/otus_highload/dating/internal/server/http"
	v1 "github.com/sterligov/otus_highload/dating/internal/server/http/handler/v1"
	"github.com/sterligov/otus_highload/dating/internal/server/http/middleware"
	"github.com/sterligov/otus_highload/dating/internal/usecase/auth"
	"github.com/sterligov/otus_highload/dating/internal/usecase/user"
)

// Injectors from wire.go:

func setup(configConfig *config.Config) (*internalhttp.Server, func(), error) {
	db, err := sql.NewDatabase(configConfig)
	if err != nil {
		return nil, nil, err
	}
	userGateway := sql.NewUserGateway(db)
	useCase := auth.NewAuthUseCase(userGateway)
	authHandler := v1.NewAuthHandler(useCase)
	userUseCase := user.NewUserUseCase(userGateway)
	userHandler := v1.NewUserHandler(userUseCase)
	ginJWTMiddleware := middleware.Auth(useCase)
	handler := v1.NewHandler(authHandler, userHandler, ginJWTMiddleware)
	server, err := internalhttp.NewServer(configConfig, handler)
	if err != nil {
		return nil, nil, err
	}
	return server, func() {
	}, nil
}
