logger:
  level: info
  path: stderr

http:
  addr: localhost:8081
  write_timeout: 5s
  read_timeout: 5s
  handler_timeout: 5s

jwt:
  secret_key: "secret_key"

database:
  connection_addr: dating_user:dating_pass@tcp(localhost:3313)/dating?parseTime=true
  driver: mysql

