logger:
  level: info
  path: stderr

http:
  addr: :8082
  write_timeout: 120s
  read_timeout: 120s
  handler_timeout: 120s

jwt:
  secret_key: secret_key

database:
  connection_addr: dating_user:dating_pass@tcp(localhost:3313)/dating?parseTime=true
  max_open_conns: 20
  max_idle_conns: 20
  max_conn_lifetime: 5m
  driver: mysql

